### ISSUE TITLE
Telegram Chat

### ISSUE THREAD

**Issue by HostFat** [wlemahieu/raiblocks.net#2]
Can you add the link to the official Telegram chat somewhere?

https://telegram.me/raiblocks

Colin is the admin.

**Comment by wlemahieu** [comment]
Sure will. I remember he mentioned this to me. I'll get that in the Social part of the footer.

**Comment by wlemahieu** [comment]
https://github.com/wlemahieu/raiblocks.net/commit/2c410b9dfdbe280e53f454053adad544e55bfc00
