### ISSUE TITLE
Claiming on Faucet

### ISSUE THREAD

**Issue by mostmodest12** [wlemahieu/raiblocks.net#7]
Hello.
Faucet needs a Texting Captchas like SolveMedia
and Claiming limit needed to be lowerer like 4-5 secs, not 6. Most people completing captcha too fast and get a error

**Comment by wlemahieu** [comment]
Why replace Google ReCaptcha with a less superior Captcha from SolveMedia?

**Comment by mostmodest12** [comment]
Not replace, do a 2 variants of captcha, what can be switched

**Comment by wlemahieu** [comment]
I don't see the advantage.
